### ISSUE TITLE
register domain

### ISSUE THREAD

**Issue by chartotu19** [waleedayoub/wine-app#10]
Options / available domains:

**pradik.at** ($23/year) - A PDO wine designation for high quality used in Germany and Austria, based on [grape ripeness] and [must w eight].

**Stravecch.io** ($70/year) - Italian term for a very old wine, often used in association with [Marsala]

**Dioecio.us** ($10/year) - A grapevine that produces either male or female flowers. Many wild grapevines are dioecious while many domesticated vines used for wine production are hermaphroditic with flowers containing both the male [staminate] features.

**pyrazin.es** ($14/year) - A group of aromatic compounds in grapes that contribute to some of the green herbaceous notes in wine from the [green bell pepper] notes in some [Cabernet Sauvignon] to the grassy notes of some [Sauvignon blanc]. In red wines, the abundance of pyrazines can be a sign that the grapes came from vines with vigorous leaf [canopy] that impeded the ripening process of the grapes.

### This is my personal favourite
** trellis.fun ($1.29/year) or trellis.plus ($13/year) - A man-made support system used in [vine-training] where shoots and cordons of grapevines are held along wires attached to posts
also **mytrellis.io** ($30/year)
and **mytrellis.club** ($2/year) <-- ### **I'm going to go ahead and buy this one**

@chartotu19 let's pick one and I'll buy it on godaddy and we can self-host it on my dreamhost.com account

**Comment by waleedayoub** [comment]
![Image](https://user-images.githubusercontent.com/5308148/187741126-a27d1676-996e-4dfe-b2a4-d7991374b87d.png)
